# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_PASSWORD: ulloa1234
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    ports:
      - 8080:8080